aws_region         = "us-east-1"
project_name       = "yelp-bigdata"
environment        = "dev"
bronze_bucket_name = "yelp-bronze-raw-us-east-1"
silver_bucket_name = "yelp-silver-clean-us-east-1"
gold_bucket_name   = "yelp-gold-analytics-us-east-1"
glue_service_role_arn = "arn:aws:iam::339712764081:role/LabRole"
